import type { SectorConfig } from '@/types'

export const SECTORS: Record<string, SectorConfig> = {
  main: {
    label: 'All AI News',
    slug: '',
    icon: '⬡',
    accent: '#00e5ff',
    description: 'The latest AI headlines curated from top publications',
    feeds: [
      'https://venturebeat.com/category/ai/feed/',
      'https://techcrunch.com/tag/artificial-intelligence/feed/',
      'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
      'https://www.technologyreview.com/feed/',
      'https://feeds.arstechnica.com/arstechnica/technology-lab',
      'https://www.wired.com/feed/category/artificial-intelligence/latest/rss',
      'https://deepmind.google/blog/rss.xml',
      'https://openai.com/news/rss/',
    ],
  },
  finance: {
    label: 'Finance',
    slug: 'finance',
    icon: '◈',
    accent: '#00ff9d',
    description: 'AI disrupting fintech, trading, banking, and investment',
    feeds: [
      'https://venturebeat.com/category/ai/feed/',
      'https://techcrunch.com/tag/artificial-intelligence/feed/',
      'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
      'https://www.wired.com/feed/category/artificial-intelligence/latest/rss',
      'https://www.technologyreview.com/feed/',
    ],
  },
  software: {
    label: 'Software & Tech',
    slug: 'software',
    icon: '◻',
    accent: '#7c3aed',
    description: 'AI in developer tools, coding assistants, and the software industry',
    feeds: [
      'https://venturebeat.com/category/ai/feed/',
      'https://techcrunch.com/tag/artificial-intelligence/feed/',
      'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
      'https://www.wired.com/feed/category/artificial-intelligence/latest/rss',
      'https://github.blog/feed/',
    ],
  },
  healthcare: {
    label: 'Healthcare',
    slug: 'healthcare',
    icon: '✦',
    accent: '#f43f5e',
    description: 'AI in diagnostics, drug discovery, patient care, and medical research',
    feeds: [
      'https://www.statnews.com/feed/',
      'https://www.healthcareitnews.com/rss.xml',
      'https://venturebeat.com/category/ai/feed/',
      'https://www.technologyreview.com/feed/',
      'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    ],
  },
  education: {
    label: 'Education',
    slug: 'education',
    icon: '◆',
    accent: '#f59e0b',
    description: 'AI reshaping tutoring, curriculum design, and ed-tech platforms',
    feeds: [
      'https://edsurge.com/rss',
      'https://venturebeat.com/category/ai/feed/',
      'https://techcrunch.com/tag/artificial-intelligence/feed/',
      'https://www.technologyreview.com/feed/',
      'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    ],
  },
  marketing: {
    label: 'Marketing & Ads',
    slug: 'marketing',
    icon: '⬖',
    accent: '#ec4899',
    description: 'How AI is transforming content creation, ad targeting, brand strategy, and growth tools',
    feeds: [
      'https://marketingaiinstitute.com/blog/rss.xml',
      'https://digiday.com/feed/',
      'https://www.searchenginejournal.com/feed/',
      'https://venturebeat.com/category/ai/feed/',
      'https://www.wired.com/feed/category/artificial-intelligence/latest/rss',
    ],
  },
  freelance: {
    label: 'Freelance Opps',
    slug: 'freelance',
    icon: '◇',
    accent: '#06b6d4',
    description: 'How to monetize AI skills — articles, tutorials, and videos',
    feeds: [
      'https://www.indiehackers.com/feed.xml',
      'https://www.producthunt.com/feed?category=artificial-intelligence',
      'https://venturebeat.com/category/ai/feed/',
      'https://techcrunch.com/tag/artificial-intelligence/feed/',
    ],
  },
  fun: {
    label: 'Fun & Weird',
    slug: 'fun',
    icon: '★',
    accent: '#a855f7',
    description: 'Quirky experiments, creative hacks, and delightfully strange AI projects',
    feeds: [
      'https://aiweirdness.com/rss',
      'https://news.ycombinator.com/showrss',
      'https://www.producthunt.com/feed?category=artificial-intelligence',
      'https://www.wired.com/feed/category/artificial-intelligence/latest/rss',
    ],
  },
}
